export const COURSES = [
  {
    slug: "intro-to-digital-marketing",
    n: "01",
    name: "Introduction to Digital Marketing",
    desc: "The foundations: how demand actually moves online, and where most Nigerian businesses lose it before they ever get to a campaign.",
    duration: "4 weeks · live sessions",
    photo: "/photos/misty-valley-mountains.jpg",
    hue: "0deg",
    whoFor: "Founders, career-switchers, and anyone who needs the full map before specialising in one channel.",
    curriculum: [
      "How demand actually forms: awareness stages and the 95/5 rule",
      "The core channels: search, social, email, and paid — what each is actually for",
      "Reading a funnel: where prospects drop off and why",
      "Setting up measurement before you spend a single naira on ads",
    ],
    outcome: "Leave with a working map of the whole discipline, so every course after this one has a place to attach to.",
  },
  {
    slug: "paid-ads",
    n: "02",
    name: "Paid Ads",
    desc: "Meta, Google, and TikTok — built around System 1 activation and frictionless conversion, not just budget and boosting.",
    duration: "5 weeks · live sessions",
    photo: "/photos/forest-sunbeams.jpg",
    hue: "0deg",
    whoFor: "Marketers and business owners running (or about to run) real ad budgets.",
    curriculum: [
      "Campaign structure across Meta, Google, and TikTok",
      "Creative that wins the instant, emotional response before rational comparison",
      "Targeting, budgets, and reading CAC/ROAS without guessing",
      "Systematic A/B testing that actually changes decisions",
    ],
    outcome: "Leave able to plan, launch, and read a paid campaign end-to-end — not just click 'boost'.",
  },
  {
    slug: "email-marketing",
    n: "03",
    name: "Email Marketing",
    desc: "Sequences and lists that build trust before they sell — the 95% content architecture applied to your inbox.",
    duration: "3 weeks · live sessions",
    photo: "/photos/river-valley-hero.jpg",
    hue: "0deg",
    whoFor: "Anyone with a list (or about to start one) who wants it to actually convert.",
    curriculum: [
      "List building that doesn't rely on discounts",
      "Sequence architecture: welcome, nurture, and conversion emails",
      "Writing subject lines and copy people actually open",
      "Deliverability basics — getting into the inbox, not the spam folder",
    ],
    outcome: "Leave with a working email sequence built during the course, not just theory.",
  },
  {
    slug: "web-design",
    n: "04",
    name: "Web Design",
    desc: "Sites built to convert intent, not just look presentable — structure, copy, and speed working together.",
    duration: "5 weeks · live sessions",
    photo: "/photos/misty-valley-mountains.jpg",
    hue: "-35deg",
    whoFor: "Designers, founders, and freelancers who want sites that perform, not just look good in a portfolio.",
    curriculum: [
      "Structuring a page around one conversion goal at a time",
      "Copy and layout working together, not fighting each other",
      "Speed and mobile performance as conversion factors, not afterthoughts",
      "A real build, start to finish, using the same principles as this site",
    ],
    outcome: "Leave having shipped one real, live page — not just a mockup.",
  },
  {
    slug: "copywriting",
    n: "05",
    name: "Copywriting",
    desc: "Words that pass the Stranger Test — clear enough that a cold reader gets it in three seconds.",
    duration: "3 weeks · live sessions",
    photo: "/photos/forest-sunbeams.jpg",
    hue: "40deg",
    whoFor: "Marketers, founders, and anyone who has to write for a business and wants it to actually land.",
    curriculum: [
      "The Stranger Test: writing so a cold reader gets it immediately",
      "Headlines, hooks, and the first three seconds of attention",
      "Writing for System 1 without sounding manipulative",
      "Editing your own work — cutting until only the necessary remains",
    ],
    outcome: "Leave with a personal editing checklist you'll use on every piece of copy you write after this.",
  },
];
